### ISSUE TITLE
Unable to understand multi-assignment statements that uses '{'

### ISSUE THREAD

**Issue by MohitHirpara** [The-OpenROAD-Project/OpenSTA#36] opened 2020-01-13 14:47 UTC
Hi,

I am unable to read a verilog that has "{" used for multi-assignment e.g.:

> assign { _5865_[8:2], _5865_[0] } = { _5861_[8:2], _5861_[0] };

Errors while using read_verilog :

```
% read_verilog netlist.v
Error: netlist.v, line 7619 syntax error, unexpected '{', expecting ID.
Error: netlist.v, line 39379 syntax error, unexpected '{', expecting ID.
Error: netlist.v, line 39380 syntax error, unexpected '{', expecting ID.
Error: netlist.v, line 39383 syntax error, unexpected '{', expecting ID.
Error: netlist.v, line 39587 syntax error, unexpected '{', expecting ID.
Error: netlist.v, line 39612 syntax error, unexpected '{', expecting ID.
```

Can you please help me figure out if I am doing some mistake or this is actually a bug ?
Thanks in Advance

**Comment by jjcherry56** [comment] 2020-01-13 15:15
this is a duplicate of issue 31

**Closed by jjcherry56** 2020-01-13 15:15 UTC
