### ISSUE TITLE
App crashes when different types of start points specified for "report_checks -from"

### ISSUE THREAD

**Issue by Blankgithub** [The-OpenROAD-Project/OpenSTA#173] opened 2023-06-28 01:55 UTC
Reproduce steps:
1. Modify last line of "examples/delay_calc.tcl" as "report_checks -from {clk u2}"
2. run OpenSTA with command "../app/sta delay_calc.tcl"
3. The app crashes.

ps: it seems that Sdc::makeFilterPath() could return a deleted exception pointer （in addException(exception)）

**Comment by jjcherry56** [comment] 2023-06-28 15:54
The issue is the the from mixes different object types (clock and instance) which the implementation isn't designed to handle. -from u2 won't work either because it is not
a start point (it needs to use -through).

**Comment by jjcherry56** [comment] 2023-06-29 03:04
fixed in commit 
8ed0b25 report_checks -from {clk inst} 
in https://github.com/parallaxsw/OpenSTA.git

**Closed by jjcherry56** 2023-06-29 03:04 UTC

**Comment by Blankgithub** [comment] 2023-06-29 05:53
> The issue is the the from mixes different object types (clock and instance) which the implementation isn't designed to handle. -from u2 won't work either because it is not a start point (it needs to use -through).

Thank you for response, James.

Do we have any plan to support mixed different object types in the future?
